### ISSUE TITLE
Attention RNN fails to compile on Tensorflow r0.10

### ISSUE THREAD

**Issue by prafiles** [tensorflow/magenta#150]
While i try to execute the following code:
`./bazel-bin/magenta/models/attention_rnn/attention_rnn_train --run_dir=/home/prakhar/Documents/Music/Magenta/outdir --sequence_example_file=/home/prakhar/Documents/Music/Magenta/dataset_dir/training_melodies.tfrecord --hparams="{'batch_size':64,'rnn_layer_sizes':[128,128]}" --num_training_steps=2000
`

I get this error thrown at me using tensorflow 0.10:
`Traceback (most recent call last):
  File "/home/prakhar/Documents/Music/Magenta/magenta/bazel-bin/magenta/models/attention_rnn/attention_rnn_train.runfiles/__main__/magenta/models/attention_rnn/attention_rnn_train.py", line 37, in <module>
    import attention_rnn_graph
  File "/home/prakhar/Documents/Music/Magenta/magenta/magenta/models/attention_rnn/attention_rnn_graph.py", line 171, in <module>
    _is_sequence = tf.nn.rnn_cell._is_sequence
AttributeError: 'module' object has no attribute '_is_sequence'
`

Same thing also happens with the master branch of tensorflow. But the issue vanishes with tensorflow r0.9. Unfortunately i have significant reasons to stick to r0.10 and if someone could point me in the direction as to what might be wrong?

**Comment by adarob** [comment]
This should be fixed by https://github.com/tensorflow/magenta/pull/148, which was merged in this morning. Are you still having the issue after doing a pull?

**Comment by prafiles** [comment]
Yes I can confirm, that with the commit ffec2883b66d3818380d4f53cc9794b7276556ca, still doesn't works with the same error as said above. Thanks for such a prompt response.

**Comment by adarob** [comment]
I see the issue. Will fix shortly.

**Comment by adarob** [comment]
Okay, should be fixed at fcbc824. Thanks for bringing this to our attention.
