### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'logging'

### ISSUE THREAD

**Issue by royleibov** [tensorflow/magenta#1573]
It seems like magenta can't load for tensorflow 2.0 as a backend.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-112-72f1d0ecb959> in <module>
     16 import IPython.display
     17 
---> 18 import magenta

~/anaconda3/lib/python3.7/site-packages/magenta/__init__.py in <module>
     32 import magenta.common.tf_utils
     33 import magenta.music.abc_parser
---> 34 import magenta.music.audio_io
     35 import magenta.music.chord_symbols_lib
     36 import magenta.music.chords_encoder_decoder

~/anaconda3/lib/python3.7/site-packages/magenta/music/__init__.py in <module>
     34 from magenta.music.chords_encoder_decoder import TriadChordOneHotEncoding
     35 
---> 36 from magenta.music.chords_lib import BasicChordRenderer
     37 from magenta.music.chords_lib import ChordProgression
     38 from magenta.music.chords_lib import extract_chords

~/anaconda3/lib/python3.7/site-packages/magenta/music/chords_lib.py in <module>
     33 from magenta.music import events_lib
     34 from magenta.music import sequences_lib
---> 35 from magenta.pipelines import statistics
     36 from magenta.protobuf import music_pb2
     37 from six.moves import range  # pylint: disable=redefined-builtin

~/anaconda3/lib/python3.7/site-packages/magenta/pipelines/statistics.py in <module>
    130 
    131 
--> 132 def log_statistics_list(stats_list, logger_fn=tf.logging.info):
    133   """Calls the given logger function on each `Statistic` in the list.
    134 

AttributeError: module 'tensorflow' has no attribute 'logging'
```

**Comment by adarob** [comment]
Perhaps you have tf 2.0 installed? For future compatibility, we should switch to absl logging, but this should work with tf 1.0 for now.

**Comment by cghawthorne** [comment]
We should also maybe look at switching to `import tensorflow.compat.v1 as tf` in most places until we actually switch to TF2.

**Comment by royleibov** [comment]
So as of now I should use tf 1.X in order to import magenta?

**Comment by iShelar** [comment]
> Perhaps you have tf 2.0 installed? For future compatibility, we should switch to absl logging, but this should work with tf 1.x for now.

How to do it? I'm not sure. I'm trying to run scripts of magenta
