### ISSUE TITLE
Installing magenta fails due to rtmidi

### ISSUE THREAD

**Issue by 2gotgrossman** [tensorflow/magenta#781]
Hi,

I'm running CentOS and am working with an anaconda Python 2.7 environment. I tried installing magenta via pip, but I get the following errors:

```
src/RtMidi.cpp:1101:28: fatal error: alsa/asoundlib.h: No such file or directory
   #include <alsa/asoundlib.h>
                              ^
  compilation terminated.

Failed to build python-rtmidi

Command "/home/davidg/anaconda2/envs/magenta/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZbHoid/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Y0KfrZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ZbHoid/python-rtmidi/
```

Happy to provide more information! Thanks for the help in advance.

**Comment by davidlecea** [comment]
I think you need to install the ALSA library development files first. Try:
sudo apt-get install libasound2-dev

**Comment by reido2012** [comment]
Make sure you have the dependencies installed 
Linux: ALSA, JACK
OS X: CoreMIDI, JACK
Windows: MultiMedia (MM)

This link has the name of the packages that you can download  - 
http://python-rtmidi.readthedocs.io/en/latest/installation.html

The commands you'll most likely need to use as stated above are:
```sudo apt-get install libasound-dev```
```sudo apt-get install libjack-dev```

**Comment by 2gotgrossman** [comment]
Thanks for the help! I was missing the ALSA library. 

Here's the commands on CentOS:
`sudo yum install alsa-lib-devel alsa-utils`

**Comment by picturedots** [comment]
I'm having a similar problem with the Mac installer (from running `bash /tmp/magenta-install.sh`) which also failed due to a problem with python-rtmidi installation.  

I'll try the docker installation instead.

**Comment by lisiping0817** [comment]
i want to know the JACK library commands in centos .how can i get it
