### ISSUE TITLE
Unable to run train command in sketch rnn

### ISSUE THREAD

**Issue by nirajpandkar** [tensorflow/magenta#1708]
**System**:
- Python: Python 3.7.7 (default, Mar 26 2020, 15:48:22)  [GCC 7.3.0] :: Anaconda, Inc. on linux
- Ubuntu 16.04 LTS
- Magenta 1.3.1

**Problem**:
Using the command
```
sketch_rnn_train --data_dir=dataset --gpu=0 --log_root=log --hparams="data_set=['eiffel_tower.npz']"
```
I get the following error -
```

/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
INFO:tensorflow:sketch-rnn
I0429 08:03:50.716002 139879426516736 sketch_rnn_train.py:430] sketch-rnn
INFO:tensorflow:Hyperparams:
I0429 08:03:50.716129 139879426516736 sketch_rnn_train.py:431] Hyperparams:
Traceback (most recent call last):
  File "/home/niraj/miniconda3/envs/magenta/bin/sketch_rnn_train", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 471, in console_entry_point
    tf.app.run(main)
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 467, in main
    trainer(model_params)
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 432, in trainer
    for key, val in six.iteritems(list(model_params.values())):
  File "/home/niraj/miniconda3/envs/magenta/lib/python3.7/site-packages/six.py", line 589, in iteritems
    return iter(d.items(**kw))
AttributeError: 'list' object has no attribute 'items'
```
I assume this is a python2/3 problem. Can someone help here? 

**Next steps for me**:
I'm going to try to downgrade python environment to 2.7 and check whether it's running. I'll update here.

**Comment by nirajpandkar** [comment]
Managed to get past that error.

Created a python2.7 conda environment. Installed magenta - `pip install magenta`. 

Was slapped with a 
```
ERROR: Failed building wheel for llvmlite
```

So installed llvmlite using conda - 
```
conda install llvmlite
```
**Note**: I also installed it system-wide using `sudo apt-get install llvm`. Don't know whether that made a difference.

Still not able to train completely. But at least past this error. Maybe can someone tell why it doesn't work in a 3.7 environment?

Thanks!

**Comment by hardmaru** [comment]
Hi,

Can you try commenting out these two lines to see if it trains in your setup?

```
  #for key, val in six.iteritems(list(model_params.values())):
  #  tf.logging.info('%s = %s', key, str(val))
```
(from [these two lines](https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/sketch_rnn_train.py#L432))

If it works, I may just remove those two lines from the repo code.

Best.

**Comment by nirajpandkar** [comment]
@hardmaru Yes I commented out those lines and it did work though **with an additional step** which I had to employ in the python2.7 environment as well - 

While loading the dataset using `np.load()`, I had to add the following parameters - 

1. If python3, `allow_pickle=True`
2. If python2, `encoding='bytes', allow_pickle=True`

```
if six.PY3:
    data = np.load(data_filepath, encoding='latin1', allow_pickle=True)
else:
    data = np.load(data_filepath, encoding='bytes', allow_pickle=True)
```
These are the [lines](https://github.com/tensorflow/magenta/blob/8e5da380a1cd39d14c5bcbbae0691e7983f833fa/magenta/models/sketch_rnn/sketch_rnn_train.py#L133)

Let me know if this breaks anything else. Otherwise I'll be happy to put in a pull request!

**Comment by hardmaru** [comment]
Sounds good, thanks for the PR! (Please also remove the two problematic lines as well when you submit it).
