### ISSUE TITLE
MusicXML Parser: Transposition is broken

### ISSUE THREAD

**Issue by jsawruk** [tensorflow/magenta#354]
When trying to read in a transposing MusicXML file I got this error:

```
musicxml_parser.py", line 413, in _parse_attributes
    self.key_signature.key += transpose
AttributeError: 'NoneType' object has no attribute 'key'
```

It appears to be a regression bug from pull request #347.

**Comment by cghawthorne** [comment]
Thanks for catching this. Could you investigate and add a unit test to verify the fix?

**Comment by cghawthorne** [comment]
Thanks, @jsawruk!
